#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
record_path="$REPO_ROOT/docs/release/manual-qa-record.md"
baseline_path=""
verification_path=""
fixture_dir=""
checksum_path=""
tester=""
notes="Prefilled from local baseline; manual QA results still required."
date_value="$(date '+%Y-%m-%d')"

usage() {
    cat <<'EOF'
Usage: scripts/prefill-manual-qa-record.sh [options]

Prefill objective build and environment fields in a manual QA record. This does
not mark manual scenarios as passed.

Options:
  --record PATH        Manual QA record to update.
  --baseline PATH      Release QA baseline generated by scripts/release-qa-baseline.sh.
  --verification PATH  Package verification report generated by scripts/verify-release-qa-package.sh.
  --checksum PATH      Package .sha256 file.
  --fixture-dir PATH   Fixture directory used for manual QA.
  --tester NAME        Fill the tester field.
  --notes TEXT         Fill the notes field.
  --date YYYY-MM-DD    Fill the date field.
  -h, --help           Show this help.
EOF
}

require_command() {
    local command_name="$1"
    if ! command -v "$command_name" >/dev/null 2>&1; then
        echo "Missing required command: $command_name" >&2
        exit 1
    fi
}

table_value() {
    local file_path="$1"
    local field_name="$2"
    awk -F'|' -v field="$field_name" '
        function trim(value) {
            gsub(/^[[:space:]]+|[[:space:]]+$/, "", value)
            gsub(/^`|`$/, "", value)
            return value
        }
        $2 {
            key = trim($2)
            if (key == field) {
                print trim($3)
                exit
            }
        }
    ' "$file_path"
}

verification_summary() {
    local report_path="$1"
    local checksum_line signature team sandbox

    checksum_line="$(awk '/: OK$/ {print; exit}' "$report_path" || true)"
    signature="$(table_value "$report_path" "Signature")"
    team="$(table_value "$report_path" "Team identifier")"
    sandbox="$(table_value "$report_path" "App Sandbox entitlement")"

    if [[ -z "$checksum_line" ]]; then
        checksum_line="checksum status not found"
    fi
    printf "%s; Signature=%s; Team=%s; Sandbox=%s" "$checksum_line" "${signature:-unknown}" "${team:-unknown}" "${sandbox:-unknown}"
}

checksum_value() {
    local file_path="$1"
    awk '{print $1; exit}' "$file_path"
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --record)
            if [[ $# -lt 2 ]]; then
                echo "--record requires a path" >&2
                exit 2
            fi
            record_path="$2"
            shift
            ;;
        --baseline)
            if [[ $# -lt 2 ]]; then
                echo "--baseline requires a path" >&2
                exit 2
            fi
            baseline_path="$2"
            shift
            ;;
        --verification)
            if [[ $# -lt 2 ]]; then
                echo "--verification requires a path" >&2
                exit 2
            fi
            verification_path="$2"
            shift
            ;;
        --checksum)
            if [[ $# -lt 2 ]]; then
                echo "--checksum requires a path" >&2
                exit 2
            fi
            checksum_path="$2"
            shift
            ;;
        --fixture-dir)
            if [[ $# -lt 2 ]]; then
                echo "--fixture-dir requires a path" >&2
                exit 2
            fi
            fixture_dir="$2"
            shift
            ;;
        --tester)
            if [[ $# -lt 2 ]]; then
                echo "--tester requires a value" >&2
                exit 2
            fi
            tester="$2"
            shift
            ;;
        --notes)
            if [[ $# -lt 2 ]]; then
                echo "--notes requires a value" >&2
                exit 2
            fi
            notes="$2"
            shift
            ;;
        --date)
            if [[ $# -lt 2 ]]; then
                echo "--date requires a value" >&2
                exit 2
            fi
            date_value="$2"
            shift
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            echo "Unknown option: $1" >&2
            usage >&2
            exit 2
            ;;
    esac
    shift
done

require_command awk
require_command date
require_command mv
require_command mktemp

if [[ -z "$baseline_path" ]]; then
    echo "--baseline is required" >&2
    usage >&2
    exit 2
fi
if [[ ! -f "$record_path" ]]; then
    echo "Manual QA record not found: $record_path" >&2
    exit 1
fi
if [[ ! -f "$baseline_path" ]]; then
    echo "Release QA baseline not found: $baseline_path" >&2
    exit 1
fi
if [[ -n "$verification_path" && ! -f "$verification_path" ]]; then
    echo "Package verification report not found: $verification_path" >&2
    exit 1
fi
if [[ -n "$checksum_path" && ! -f "$checksum_path" ]]; then
    echo "Checksum file not found: $checksum_path" >&2
    exit 1
fi

git_commit="$(table_value "$baseline_path" "Git commit")"
app_path="$(table_value "$baseline_path" "App path")"
version_build="$(table_value "$baseline_path" "Version / build")"
signature="$(table_value "$baseline_path" "App signature")"
team_identifier="$(table_value "$baseline_path" "Team identifier")"
identity_count="$(table_value "$baseline_path" "Available local code signing identities")"
sandbox_status="$(table_value "$baseline_path" "App Sandbox entitlement")"
architecture="$(table_value "$baseline_path" "Architecture")"
cpu="$(table_value "$baseline_path" "CPU")"
macos="$(table_value "$baseline_path" "macOS")"
xcode_version="$(table_value "$baseline_path" "Xcode version")"
distribution_status="$(table_value "$baseline_path" "Distribution signing status")"

signing_identity="Signature=${signature:-unknown}; Team=${team_identifier:-unknown}; Local identities=${identity_count:-unknown}; Sandbox=${sandbox_status:-unknown}"
current_environment="${architecture:-unknown}; ${cpu:-unknown}; macOS ${macos:-unknown}; ${xcode_version:-unknown}"

package_sha="not provided"
if [[ -n "$checksum_path" ]]; then
    package_sha="$(checksum_value "$checksum_path")"
fi

package_verification="not provided"
if [[ -n "$verification_path" ]]; then
    package_verification="$(verification_summary "$verification_path")"
fi

fixture_value="not provided"
if [[ -n "$fixture_dir" ]]; then
    fixture_value="$fixture_dir"
fi

tmp_path="$(mktemp "${TMPDIR:-/tmp}/manual-qa-record-prefill.XXXXXX")"

while IFS= read -r line || [[ -n "$line" ]]; do
    case "$line" in
        "| Date | "*)
            printf "| Date | %s |\n" "$date_value" >>"$tmp_path"
            ;;
        "| Tester | "*)
            if [[ -n "$tester" ]]; then
                printf "| Tester | %s |\n" "$tester" >>"$tmp_path"
            else
                printf "%s\n" "$line" >>"$tmp_path"
            fi
            ;;
        "| Git commit | "*)
            printf "| Git commit | \`%s\` |\n" "${git_commit:-unknown}" >>"$tmp_path"
            ;;
        "| App path | "*)
            printf "| App path | \`%s\` |\n" "${app_path:-unknown}" >>"$tmp_path"
            ;;
        "| Version / build | "*)
            printf "| Version / build | \`%s\` |\n" "${version_build:-unknown}" >>"$tmp_path"
            ;;
        "| Signing identity | "*)
            printf "| Signing identity | \`%s\` |\n" "$signing_identity" >>"$tmp_path"
            ;;
        "| Package SHA-256 | "*)
            printf "| Package SHA-256 | \`%s\` |\n" "$package_sha" >>"$tmp_path"
            ;;
        "| Package verification | "*)
            printf "| Package verification | %s |\n" "$package_verification" >>"$tmp_path"
            ;;
        "| Fixture directory | "*)
            printf "| Fixture directory | \`%s\` |\n" "$fixture_value" >>"$tmp_path"
            ;;
        "| Notes | "*)
            printf "| Notes | %s |\n" "$notes" >>"$tmp_path"
            ;;
        "| Apple Silicon | "*)
            if [[ "${architecture:-}" == "arm64" ]]; then
                printf "| Apple Silicon | %s | ⬜ Not run | Baseline captured locally; manual menu bar and restore evidence still required. |\n" "$current_environment" >>"$tmp_path"
            else
                printf "%s\n" "$line" >>"$tmp_path"
            fi
            ;;
        "| Current macOS | "*)
            printf "| Current macOS | %s | ⬜ Not run | Baseline captured; manual Release workflow evidence still required. |\n" "$current_environment" >>"$tmp_path"
            ;;
        "| Blocking issues | "*)
            printf "| Blocking issues | %s |\n" "${distribution_status:-Manual QA and signing review still required.}" >>"$tmp_path"
            ;;
        *)
            printf "%s\n" "$line" >>"$tmp_path"
            ;;
    esac
done <"$record_path"

mv "$tmp_path" "$record_path"

echo "Manual QA record prefilled:"
echo "  Record:       $record_path"
echo "  Baseline:     $baseline_path"
if [[ -n "$verification_path" ]]; then
    echo "  Verification: $verification_path"
fi
if [[ -n "$checksum_path" ]]; then
    echo "  SHA-256:      $checksum_path"
fi
if [[ -n "$fixture_dir" ]]; then
    echo "  Fixtures:     $fixture_dir"
fi
echo
echo "Manual results remain unset; run scripts/validate-manual-qa-record.sh after completing QA."
